development:
  adapter: postgresql
  encoding: unicode
  database: development
  username: postgres
  password: 9summer9
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: development
  username: postgres
  password: 9summer9
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: development
  username: postgres
  password: 9summer9
  host: localhost
  port: 5432
